name: color_filter_extension

description: "Comprehensive Flutter color filter library with 30+ professional filters & 90+ presets. Includes film emulation, cinema looks, artistic effects, and technical adjustments."
version: 1.0.0
homepage: https://github.com/dipendra-sharma/flutter_color_filter_extension

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: