name: color_filter_extension

description: "Flutter image magic! ColorFilter lets you adjust brightness, contrast, & apply presets with ease. Perfect for app design, artistic effects, & photo processing"
version: 0.1.0
homepage: https://github.com/dipendra-sharma/flutter_color_filter_extension

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: